apiVersion: v1
kind: Secret
metadata:
  name: mtls-certs
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_SERVER_CERT>
  tls.key: <BASE64_ENCODED_SERVER_KEY>
  ca.crt: <BASE64_ENCODED_CA_CERT>
